"use client";
import {createContext,useContext,useEffect,useState} from "react";
import {analyzeDocumentAction,createProjectAction,uploadDocumentAction,uploadProposalAction} from "@/app/actions";
import type {DocType,Project,ReqStatus,Workspace} from "@/lib/domain";
const C=createContext<null|(Workspace&{createProject:(v:Omit<Project,"id"|"status"|"updatedAt">)=>Promise<Project>;addDocument:(p:string,f:File,t:DocType)=>Promise<Workspace["documents"][number]>;addProposal:(p:string,f:File)=>Promise<Workspace["proposals"][number]>;setReq:(id:string,s:ReqStatus)=>void;resolve:(id:string)=>void})>(null);
export function Provider({children,initialData}:{children:React.ReactNode;initialData:Workspace}){const [d,setD]=useState(initialData);
 useEffect(()=>{localStorage.setItem("procureai-v2",JSON.stringify(d))},[d]);
 const value={...d,async createProject(v:Omit<Project,"id"|"status"|"updatedAt">){const p=await createProjectAction(v);setD(x=>({...x,projects:[p,...x.projects]}));return p},async addDocument(projectId:string,file:File,type:DocType){const formData=new FormData();formData.set("projectId",projectId);formData.set("documentType",type);formData.set("file",file);const uploaded=await uploadDocumentAction(formData);setD(x=>({...x,documents:[uploaded,...x.documents]}));const analyzed=await analyzeDocumentAction(uploaded.id);setD(x=>({...x,documents:x.documents.map(document=>document.id===analyzed.document.id?analyzed.document:document),requirements:[...analyzed.requirements,...x.requirements.filter(requirement=>!analyzed.requirements.some(item=>item.id===requirement.id))]}));return analyzed.document},async addProposal(projectId:string,file:File){const formData=new FormData();formData.set("projectId",projectId);formData.set("file",file);const proposal=await uploadProposalAction(formData);setD(x=>({...x,proposals:[proposal,...x.proposals.filter(y=>y.projectId!==projectId)]}));return proposal},setReq(id:string,s:ReqStatus){setD(x=>({...x,requirements:x.requirements.map(r=>r.id===id?{...r,status:s}:r)}))},resolve(id:string){setD(x=>({...x,issues:x.issues.map(i=>i.id===id?{...i,status:"resolved"}:i)}))}};return <C.Provider value={value}>{children}</C.Provider>}
export const useWorkspace=()=>{const v=useContext(C);if(!v)throw new Error("Provider missing");return v};
